// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Title struct {
	TitleID int64  `json:"title_id"`
	Title   string `json:"title"`
}

type User struct {
	UserId    int64       `json:"userId"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Phone     pgtype.Text `json:"phone"`
	Region    pgtype.Text `json:"region"`
	Gender    pgtype.Text `json:"gender"`
	TitleID   int32       `json:"title_id"`
	FirstName string      `json:"firstName"`
	LastName  string      `json:"lastName"`
	Age       pgtype.Int2 `json:"age"`
}
