// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
