// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: Titles.sql

package db

import (
	"context"
)

const createTitles = `-- name: CreateTitles :one
INSERT INTO "Titles" (
    title
) VALUES (
    'MR.'
)
RETURNING title_id, title
`

func (q *Queries) CreateTitles(ctx context.Context) (Title, error) {
	row := q.db.QueryRow(ctx, createTitles)
	var i Title
	err := row.Scan(&i.TitleID, &i.Title)
	return i, err
}
