// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user_roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUserRoles = `-- name: CreateUserRoles :one
INSERT INTO "user_roles" (
    role, role_description
) VALUES (
    $1, $2
)

RETURNING user_id, role, role_description, create_at, update_at
`

type CreateUserRolesParams struct {
	Role            int32       `json:"role"`
	RoleDescription pgtype.Text `json:"role_description"`
}

func (q *Queries) CreateUserRoles(ctx context.Context, arg CreateUserRolesParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, CreateUserRoles, arg.Role, arg.RoleDescription)
	var i UserRole
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.RoleDescription,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
